[2020-06-02 22:04:12,129] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_simple_dag.load 2020-06-02T09:44:00+00:00 [queued]>
[2020-06-02 22:04:12,141] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_simple_dag.load 2020-06-02T09:44:00+00:00 [queued]>
[2020-06-02 22:04:12,141] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-02 22:04:12,141] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-02 22:04:12,141] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-02 22:04:12,176] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): load> on 2020-06-02T09:44:00+00:00
[2020-06-02 22:04:12,182] {standard_task_runner.py:53} INFO - Started process 31686 to run task
[2020-06-02 22:04:12,260] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: my_simple_dag.load 2020-06-02T09:44:00+00:00 [running]> nineleaps-ThinkPad-E470
[2020-06-02 22:04:12,275] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory: 'airflow_home/my_pipeline/My Project-3b4aa17f4859.json'
Traceback (most recent call last):
  File "/home/nineleaps/Desktop/work_from_home_assignments/python_assignment/asf/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/Desktop/work_from_home_assignments/python_assignment/asf/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/Desktop/work_from_home_assignments/python_assignment/asf/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/Desktop/work_from_home_assignments/python_assignment/asf/airflow_home/pwd/dags/my_simple_dag.py", line 112, in load_data_func
    output_rows = load_data(report_name)
  File "/home/nineleaps/Desktop/work_from_home_assignments/python_assignment/asf/airflow_home/pwd/dags/my_simple_dag.py", line 62, in load_data
    scopes=["https://www.googleapis.com/auth/cloud-platform"],
  File "/home/nineleaps/Desktop/work_from_home_assignments/python_assignment/asf/venv/lib/python3.6/site-packages/google/oauth2/service_account.py", line 218, in from_service_account_file
    filename, require=["client_email", "token_uri"]
  File "/home/nineleaps/Desktop/work_from_home_assignments/python_assignment/asf/venv/lib/python3.6/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_home/my_pipeline/My Project-3b4aa17f4859.json'
[2020-06-02 22:04:12,276] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=my_simple_dag, task_id=load, execution_date=20200602T094400, start_date=20200602T163412, end_date=20200602T163412
[2020-06-02 22:04:22,081] {logging_mixin.py:112} INFO - [2020-06-02 22:04:22,080] {local_task_job.py:103} INFO - Task exited with return code 1
